### ISSUE TITLE
install dependencies before run npm install

### ISSUE THREAD

**Issue by fernandoneto** [cusspvz/node.docker#1]
It should be possivel to install dependencies before run npm install. 

example:

A project that need python package will fail on npm install because this package only will be installed after npm install

``` bash
ONBUILD ADD . /app
ONBUILD RUN npm install --production
ONBUILD RUN npm run build
```

error output for missing python package

```
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:114:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:47:11
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:72:25)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/mmmagic
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

```

**Comment by fernandoneto** [comment]
One solution could be providing a script that read a file in project root path.
 Ex. `.dependencies`. 
The script look for this file, and if it doesn't exist build process continue, else install dependencies and  continue with build process.

**Comment by cusspvz** [comment]
Followed **Docker Docs** guidelines and separated `onbuild` feature into a different tag.
Please read changes I've made into `README.md`.

In your case you will need to do:

```
FROM cusspvz/node:0.12.7
RUN #Dependencies installs here
ENV NODE_ENV=production 
ADD . /app
RUN npm install --production
RUN npm run build
CMD [ "start" ]

```

**Comment by cusspvz** [comment]
If you want to propose some sort of package dependencies as you said, please re-open a new issue for discussion. Thanks @fernandoneto .

**Comment by cusspvz** [comment]
You may need to wait a little bit while DockerHub is re-building tags (didn't wanted to do it manually, so I've created a script to hack into theirs UI and inject tags. :P )
