### ISSUE TITLE
Add yarn

### ISSUE THREAD

**Issue by matteocng** [cusspvz/node.docker#10]
Could we add [yarn](/yarnpkg/yarn), initially by installing it globally with npm and then by adding the apk package, when Daniel15/yarn@932e90e30f0d7bcf10418bd03a75853c14925839 gets unblocked and merged?

**Comment by cusspvz** [comment]
Hello @matteocng,

Thanks for noticing it. It would be great to support yarn, however, it could introduce unneeded code to those who aren't using it. Do you think a `tag` separated `onbuild` such as `onbuild-yarn` would be a solution?

Cheers

**Comment by matteocng** [comment]
@cusspvz that would be nice, thanks 👍
