### ISSUE TITLE
Versioned `:development` tags?

### ISSUE THREAD

**Issue by agilgur5** [cusspvz/node.docker#7]
In case I need to build my front end code with a specific version of `node` or `npm`, for instance

**Comment by cusspvz** [comment]
I think [versioned development images](https://github.com/cusspvz/node.docker/blob/master/.travis.yml#L268) are already being built on travis.

Have you tested pulling `cusspvz/node:version-development`?
Example: `cusspvz/node:4.0.0-development`

**Comment by cusspvz** [comment]
Gonna close for now, please feel free to ask for a reopen in case you detect any anomaly.

**Comment by agilgur5** [comment]
Oh, there are -- not sure how I missed that in the images list! I was probably confused because the README section for using the regular and `onbuild` image both references versions, but the `development` section doesn't. Thanks for the quick reply, I'll be using the image ASAP! :)
