### ISSUE TITLE
not support node v6 yet?

### ISSUE THREAD

**Issue by huan** [cusspvz/node.docker#8]
I love alpine & node6 & onbuild, when will we have that?

**Comment by cusspvz** [comment]
Added it on fde1e16f7f22c8cd14e8e0ea72ae9e5e918dded7

Gonna check if it is stable before adding them to the README.md

**Comment by cusspvz** [comment]
If you're willing to test them as well, you can check the [build status here](https://travis-ci.org/cusspvz/node.docker/builds/150037139).

**Comment by huan** [comment]
your travis ci looks crazy, it's so many versions! :-]

I use node v6 for a while, it works well for me. 

will test your image(and onbuild it) later, thanks!

**Comment by cusspvz** [comment]
Yeah, I know, I'm gonna remove old versions later. No one uses and I am not maintaining them.

**Comment by cusspvz** [comment]
```
josemoreira@MBP-de-JM ~> node.docker 6.3.1
Unable to find image 'cusspvz/node:6.3.1' locally
6.3.1: Pulling from cusspvz/node

e587fa4f6e1f: Pull complete
a3ed95caeb02: Pull complete
285cc0167282: Pull complete
9473471883c6: Downloading [===================================>               ] 9.677 MB/13.81 MB
80d0e21eee3a: Download complete
9473471883c6: Pull complete
80d0e21eee3a: Pull complete
21ea13acaad1: Pull complete
Digest: sha256:c381ad9880d1709a677850ce770daaaa6159a93c2de9a950815cb134399bd167
Status: Downloaded newer image for cusspvz/node:6.3.1


>
>
> process.env
{ NODE_VERSION: '6.3.1',
  HOSTNAME: 'db9d4f3d5068',
  TERM: 'xterm',
  NODE_PREFIX: '/usr/local',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  PWD: '/app',
  SHLVL: '0',
  HOME: '/root',
  no_proxy: '*.local, 169.254/16' }
>
(To exit, press ^C again or type .exit)
>
josemoreira@MBP-de-JM ~> docker run -ti cusspvz/node:6.3.1 bash
/app # node -v
v6.3.1
/app # exit
josemoreira@MBP-de-JM ~>
```

Seems the built went well.

**Comment by huan** [comment]
yes, cool & thanks!

**Comment by cusspvz** [comment]
Added independent travis jobs and a deployment way that only updates images if there were changes on it.

Please check the new README.

**Comment by huan** [comment]
great! :+1:
